### PR TITLE
Add Folder Contents Details Panel, Improve Documentation

### PR DESCRIPTION
**Pull request by RandomExplosion**
I have implemented the double click to view folder details/open file.
As well as made some small documentation changes

### CODE REVIEW

**Comment by RandomExplosion** [comment]
works fine on my machine

**Comment by Nigecat** [comment]
If the `File Name` header on the upper right panel is clicked without having a folder open it causes the program to crash.

**Comment by RandomExplosion** [comment]
Ok, I can reproduce the bug and have identified the cause
Implimenting Fix Now.

**Comment by Nigecat** [comment]
And once you enter a directory through the file browser on the right panel there is no way to navigate up a directory from what I can tell. Maybe have an extra folder named `..` at the top to go up a directory.

**Comment by Nigecat** [comment]
If a file is selected on the left panel and you attempt to open a file on the right it opens the file you clicked plus the file that is selected on the left panel at the same time.

**Comment by RandomExplosion** [comment]
@Nigecat Does that problem still persist?

**Comment by RandomExplosion** [comment]
Found Bug where program errors if you open a file with no associated app in the right panel.
Have fixed it

**Comment by RandomExplosion** [comment]
Ok @Nigecat I am looking into the open multiple times bug now

**Review by Nigecat — APPROVED** [review]
Looks Good!

**Pull request merged**
